spring: 
   datasource:
    url: jdbc:mysql://localhost:3306/banco?serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8080    
    
   