spring: 
  h2:
    console:
      enabled: true
      path: /console   
  datasource:
#    url: jdbc:mysql://localhost:3306/banco?serverTimezone=UTC
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
   url: jdbc:h2:file:~/banco
   username: sa
   password: sa
   driverClassName: org.h2.Driver
  jpa:  
    generate-ddl: true
    hibernate:
      ddl-auto: update  
server:
  port: 8080    
    
   