spring: 
   datasource:
    url: jdbc:mysql://localhost:3306/banco?serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
   jpa:  
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8080    
    
   